version: "3.7"

services:
  flaskapitemplate:
    build:
      context: ./
      dockerfile: release.Dockerfile
    container_name: flask-api-template
    restart: always
    env_file:
      - app/dev.env
    volumes:
      - "./app:/app"
    ports:
      - "80:80"